# Generated by Django 5.2.9 on 2025-12-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ocr_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
